name: Download Artifact
on: 
  push:
    branches: 
      - main
      - dev

  pull_request: 
    branches: 
      - main
      - dev
  
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    strategy:
      # Permetre de tout arrêter en cas d'échec d'un job
      fail-fast: true
      # n'execute que 2 jobs en // à la fois
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [16, 18, 20]
        include:
          - os: windows-latest
            version: 22
        exclude:
          - os: ubuntu-latest
            version: 16
          - os: windows-latest
            version: 18
          - os: macos-latest
            version: 20

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-node${{ matrix.version }}
          path: dist/

  conditional-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    steps:
      - name: Download artifact (Ubuntu + Node 18)
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu-latest-node18
          path: ./artifact

      - name: Simulate deployment
        run: |
          echo "Deploying build from Ubuntu + Node 18"
          ls ./artifact